version: 0.2

phases:
  install:
    commands:
      - echo Install started on `date`
      - pip3 install cfn-lint
      - pip3 install cfnexec
      - pip3 install taskcat
      - gem install cfn-nag
      - curl --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/aws-cloudformation/cloudformation-guard/main/install-guard.sh | sh
      - export PATH="$PATH:~/.guard/bin/"
  pre_build:
    commands:
      - echo Install completed on `date`
      - echo Initialize start on `date`
      - python3 start.py -c ./config.yml -s3 `python3 get_value.py -c  ./config.yml -k bucket_url_key`
      - echo Initialize completed on `date`
      - echo cfn-validate start on `date`
      - aws cloudformation validate-template --template-body file://`python3 get_value.py -c  ./config.yml -k template`
      - echo cfn-validate completed on `date`
      - echo cfn-lint start on `date`
      - cfn-lint `python3 get_value.py -c  ./config.yml -k template`
      - echo cfn-lint completed on `date`
      - echo cfn-nag start on `date`
      - cfn_nag_scan --input-path `python3 get_value.py -c  ./config.yml -k template`
      - echo cfn-lint completed on `date`
      - echo cfn-nag start on `date`
      - cfn-guard validate -d `python3 get_value.py -c  ./config.yml -k template` -r ./rule.ruleset
      - echo cfn-nag completed on `date`
      - echo taskcat start on `date`
      - taskcat test run
  build:
    commands:
      - echo taskcat completed on `date`
      - echo deploy start on `date`
      - cfn-exec -n `python3 get_value.py -c  ./config.yml -k name` -i `python3 get_value.py -c  ./config.yml -k template` -p `python3 get_value.py -c  ./config.yml -k parameter` -s3 `python3 get_value.py -c  ./config.yml -k bucket_url_key`
  post_build:
    commands:
      - echo deploy completed on `date`
      - echo close on `date`
      # - python3 close.py -c ./config.yml
      - yes | bash delete-s3bucket.sh `python3 get_value.py -c  ./config.yml -k name`*
